name: Deploy to Azure

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Azure CLI info
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az login -u ${{ secrets.AZURE_USER }} -p ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Azure CLI info
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: ./etc/azure

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./etc/azure

    - name: Save Connection String
      run: echo "ConnectionStrings__Default=$(terraform output --raw connection_string)" >> $GITHUB_STATE
      working-directory: ./etc/azure

    - name: (DEBUG) Shows Connection String
      run: echo "ConnectionStrings__Default=$(terraform output --raw connection_string)" >> $GITHUB_OUTPUT
      working-directory: ./etc/azure

    - name: Run Migrator Console App
      run: dotnet run --project ./src/QuizHero.DbMigrator
