name: Deploy to Azure

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        auth-type: IDENTITY
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Azure CLI info
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: ./etc/azure

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./etc/azure

    - name: Save Connection String
      run: echo "ConnectionStrings__Default=$(terraform output --raw connection_string)" >> $GITHUB_STATE
      working-directory: ./etc/azure

    - name: (DEBUG) Shows Connection String
      run: echo "ConnectionStrings__Default=$(terraform output --raw connection_string)" >> $GITHUB_OUTPUT
      working-directory: ./etc/azure

    - name: Run Migrator Console App
      run: dotnet run --project ./src/QuizHero.DbMigrator
